ZenBit-Tech/ctrlchamps_fe

- src/assets/icons/ArrowBackFilled.tsx
- src/assets/icons/NeedHelpIcon.tsx
- src/components/reusable/ErrorText.tsx
- src/components/reusable/FilledButton.tsx
- src/components/reusable/header/index.tsx
- src/components/reusable/header/styles.ts
- src/theme/colors.ts
- src/theme/fonts.ts
- I made reusable header component for signup section and set up colors and fonts. Also, some additional reusable components were made (FilledButton, ErrorText) as well as imported icons needed for signupHeader.
> feat: make reusable header + create common theme

- src/assets/icons/CloseIcon.tsx
- src/components/reset-password-form/ResetPasswordForm.tsx
- src/components/reusable/header/FlowHeader.tsx
- src/components/reusable/header/styles.ts
- src/components/reusable/index.tsx
- src/components/verification/OTPInput.tsx
- src/components/verification/Verification.tsx
- src/components/verification/styles.ts
- src/locales/langs/en.ts
- I adopted the reusable header which we have to suit project's further needs.  Now, there is an option for 'back' icon and 'close' icon. Also, MainHeader component will be made in the near future which will contain user icon, logo and appointments.
> feat: adopt first reusable header

- src/locales/langs/en.ts
create Complete profile fifth component
update error messages
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-73l)
> feat: compete profile 5 FE

- src/components/sign-up-fourth/index.tsx
- src/components/sign-up-fourth/style.ts
- src/components/sign-up-fourth/validation.ts
- Fixed mentioned on demo issue with password field on fourth step of sign-up process.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-7?atlOrigin=eyJpIjoiYjkzMzI3OTgwNTgzNDlmZGFkZDU1YTNiNzBkNmNjZDMiLCJwIjoiaiJ9)
screenshots:
> fix: change password field logic

- src/components/complete-profile-fifth/CompleteProfileFifth.tsx
- src/components/complete-profile-fourth/CompleteProfileFourth.tsx
- src/components/complete-profile-second/CompleteProfileSecond.tsx
- src/components/complete-profile-second/work-form/WorkForm.tsx
- src/components/complete-profile-second/work-form/styles.ts
- src/components/complete-profile-second/work-list/WorkList.tsx
- src/components/complete-profile-third/CompleteProfileThird.tsx
- src/components/complete-profile-third/types.ts
- src/components/profile/bio/Bio.tsx
- src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
- src/components/profile/profile-qualification/certificate-form/styles.ts
- src/components/reusable/profile-btn/ProfileBtn.tsx
- src/components/reusable/profile-btn/styles.ts
- src/locales/langs/en.ts
- src/pages/profile/index.tsx
add Back Button to Profile button component;
updated profile page;
add onBack props to 2-6 Complete profile components; 
removed icon from Complete profile header
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-147)
> fix: updated common styles of Complete profile

- src/components/complete-profile-fourth/CompleteProfileFourth.tsx
- src/components/complete-profile-fourth/constants.ts
- src/components/complete-profile-fourth/hooks.ts
- src/components/complete-profile-fourth/styles.ts
- src/components/complete-profile-fourth/types.ts
- src/components/create-appointment/AppointmentScheduling.tsx
- src/components/create-appointment/AppointmentType.tsx
- src/components/create-appointment/OneTimeAppointment.tsx
- src/components/create-appointment/RecurringAppointment.tsx
- src/components/create-appointment/constants.ts
- src/components/create-appointment/styles.ts
- src/locales/langs/en.ts
- src/utils/calculateTimeDifference.ts
- src/utils/defineCustomTime.ts
- src/utils/extractTimeFromDate.ts
- src/utils/generateTime.ts
- I changed profile availability logic so that when the user chooses start time then the end time's value should automatically be + 1 hour. also the end time can't be less than the start time. 
- in profile the logic was moved to custom hook
Also the user cannot choose identical time:
- the time handling logic was refactored and am/pm format was removed from selects and from logic.
- at the appointment page in type of an appointment startDate/endDate and startTime/endTime are taken from the appointment slice so that when the user go back to one step, he/she could see all the info entered at previous step
> refactor: refactor time functionality

- src/components/appointments/Appointments.tsx
- src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
- src/components/appointments/appointment-drawer/styles.ts
- src/components/appointments/appointment-status/AppointmentStatus.tsx
- src/components/appointments/appointment-status/styles.ts
- src/components/appointments/appointments-list/AppointmentsList.tsx
- src/components/appointments/appointments-list/styles.ts
- src/components/appointments/cancel-modal/CancelModal.tsx
- src/components/appointments/cancel-modal/styles.ts
- src/components/appointments/constants.ts
- src/components/appointments/helpers.ts
- src/components/appointments/styles.ts
- src/components/appointments/types.ts
- src/constants/index.ts
- src/locales/langs/en.ts
- src/pages/index.tsx
- src/theme/colors.ts
- src/theme/fonts.ts
add Appointments component;
add Appointment status component;
add Appointments list component;
add Cancel Modal;
add Appointment Drawer Component for all statuses types; 
used mocked data, because we don't have BE part for this component now
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-127)
Appointments page:
Drawer for 'Pending confirmation' status:
Drawer for 'Active' status:
Drawer for 'Accepted' status:
Drawer for 'Virtual assessment' status:
Drawer for 'Rejected' status:
Cancel appointment modal:
> Feat: FE Appointments page

- src/components/profile/profile-qualification/certificate-form/validation.ts
- src/locales/langs/en.ts
- I added validation for start date input (we had validation only for the date picker).
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-207?atlOrigin=eyJpIjoiNTllN2ZiNjBiMDEzNGNjNTg5MDZiYTRkZmRmYzdiOGUiLCJwIjoiaiJ9)
> fix: start date cannot be in future

- src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
- src/theme/overrides/Tabs.ts
- Fixed caregiver drawer to let user access services tab via arrows
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-272?atlOrigin=eyJpIjoiM2IwNDNhNDM4YjlkNGEyNWEzZjVkY2M2NzhkZGZmYmQiLCJwIjoiaiJ9)
> fix: fix tab arrows and styling

- src/components/appointments/AppointmentsPage.tsx
- src/components/caregiver-schedule/CaregiverSchedulePage.tsx
- src/components/reusable/header/MainHeader.tsx
- src/components/reusable/header/enums.ts
- src/components/reusable/header/styles.ts
- src/pages/account-details/index.tsx
- src/routes/index.ts
- I adjusted main header so that on 'appointments/schedule' onclick, the user was redirected to the respective page and could see his/her appointments. Also, adjusted the logic on current pages. Removed 'chats' tab as we are not sure if we will have time to implement this feature. Added styles and redirect for notification icon.
> fix: adjust main header logic

- src/components/confirm-appointment/ConfirmAppointment.tsx
- src/components/create-appointment-fourth/CreateAppointmentFourthDrawer.tsx
- I changed logic so that the user could view caregiver's profile on 'confirm appointment' step instead of going back to 'find caregiver' step.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-259)
> fix: change logic to open caregiver drawer on confirm appointment step

- src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
- src/components/appointments/appointment-drawer/activity-log-modal/helpers.ts
- src/components/appointments/appointment-drawer/activity-log-modal/styles.ts
- src/components/appointments/appointment-drawer/hooks.ts
- src/components/appointments/appointment-drawer/review-activity-log-modal/RejectReviewActivityLogModal.tsx
- src/components/appointments/appointment-drawer/review-activity-log-modal/ReviewActivityLogModal.tsx
- src/components/appointments/appointment-drawer/review-activity-log-modal/helpers.ts
- src/components/appointments/appointment-drawer/review-activity-log-modal/styles.ts
- src/components/appointments/appointment-drawer/review-activity-log-modal/validation.ts
- src/components/appointments/appointments-list/AppointmentsList.tsx
- src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
- src/components/virtual-assessment-request/types.ts
- src/locales/langs/en.ts
- src/redux/api/activityLogApi.ts
- Added review activity log modal.
- Added reject review activity log modal.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-151?atlOrigin=eyJpIjoiYmZkODRiM2ZkM2JlNDg0ZjlkMWJjNWRlNDdkMzcyMmMiLCJwIjoiaiJ9)
> feat: add review activity log

- src/components/confirm-appointment/ConfirmAppointment.tsx
- src/redux/slices/healthQuestionnaireSlice.ts
- I added logic of resetting all appointment info after it has been created + the button should be disabled if there is ongoing request.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-304)
> fix: reset all appointment info after it has been created

- src/components/complete-profile-fifth/CompleteProfileFifth.tsx
- src/components/complete-profile-third/CompleteProfileThird.tsx
- removed IsDirty from Next button in Services and Rate. Now user can click Next even if he didn't change services or rate
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-306)
> fix: Complete profile 3,5

- src/components/faq-accordion/FaqAccordion.tsx
- Changed default faq accordion icon
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-193?atlOrigin=eyJpIjoiYjRiYWEyMjc4NzBjNDAxYTllN2EwYmRmZmE4ZTczNTQiLCJwIjoiaiJ9)
> fix: change default accordion icon

- src/components/create-appointment/OneTimeAppointment.tsx
- src/locales/langs/en.ts
I fixed one-time appointment logic so that the user couldn't choose identical time and the end time would not exceed the start time.
> fix: fix one-time appointment logic

- src/components/account-details/AccountDetails.tsx
- src/components/account-details/styles.ts
- src/locales/langs/en.ts
- updated button text. If there is avatar - 'Update photo', if not - 'Upload photo'
- moved trash button.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-316)
> fix: update avatar button text

- src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
- src/components/appointments/appointment-drawer/styles.ts
- src/locales/langs/en.ts
- updated styles of buttons for appointments with status 'Pending confirmation'
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-313)
for Caregiver:
for Client:
> fix: updated button's styles in appointment request

- src/components/account-details/AccountDetails.tsx
- src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
- src/components/appointments/appointment-drawer/styles.ts
- src/components/appointments/complete-appointment-modal/CompleteAppointmentModal.tsx
- src/components/appointments/constants.ts
- src/components/appointments/helpers.ts
- src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
- src/components/caregiver-schedule/CaregiverAppointment.tsx
- src/components/caregiver-schedule/styles.ts
- src/components/confirm-appointment/ConfirmAppointment.tsx
- src/components/create-appointment-fourth/CreateAppointmentFourth.tsx
- src/components/create-appointment-fourth/constants.ts
- src/components/create-appointment-fourth/helpers.ts
- src/components/create-appointment-fourth/styles.ts
- src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
- src/components/reusable/drawer/caregiver-drawer/constants.ts
- src/components/reusable/drawer/caregiver-drawer/styles.ts
- src/components/reusable/header/MainHeader.tsx
- src/components/reusable/user-avatar/UserAvatar.tsx
- src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
- src/constants/index.ts
- src/redux/api/userApi.ts
- added user avatar reusable component;
- added user photo from database to main header, appointment drawer, modals, schedule page, create appointment(caregivers list, confirm appointment), caregiver drawer;
- updated userApi;
- moved avatar sizes to global constants;
- removed get mocked avatar function.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-254)
header:
appointment drawer:
caregiver drawer:
caregivers list:
confirm appointment:
virtual assessment:
schedule page:
complete appointment modal:
> feat: add avatar from db to all components

- src/components/account-details/update-password-form/UpdatePassword.tsx
- src/hooks/useCustomForm.ts
- I added a custom hook for trimming input values. Now if it's needed, field 'trim' can be passed to useForm and it would get rid of spaces in inputs.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-317)
> fix: create custom hook for trimming input spaces

- src/components/complete-profile-second/work-form/WorkForm.tsx
- src/components/complete-profile-second/work-form/validation.ts
- src/locales/langs/en.ts
- updated work experience date validation;
- added error messages
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-267)
> fix: work experience date validation

- src/components/account-details/update-password-form/UpdatePassword.tsx
- I fixed update password displaying message. Now the message is not displayed if new password and confirm password fields are valid.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-335)
> fix: fix confirm password bug

- src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
- src/components/profile/profile-qualification/certificate-form/validation.ts
- src/locales/langs/en.ts
- I fixed bug that expiration date can be set earlier than today.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-328?atlOrigin=eyJpIjoiNzA2ODM1NzMzMzVkNDI2N2I5Yjk5MGM1ZDE0MTcyOWQiLCJwIjoiaiJ9)
> fix: expiration date can be set earlier than today

- src/components/appointments/appointment-drawer/hooks.ts
- src/components/appointments/constants.ts
- src/components/appointments/helpers.ts
- src/components/appointments/virtual-assessment-modal/helpers.ts
- src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
- src/components/confirm-appointment/ConfirmAppointment.tsx
- src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
- Now appointment time displayed with timezone of appointment
- Virtual assessment time applies to current timezone of user
- Time and date values are converted to UTC before sending to backend
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?selectedIssue=CC-346)
> fix: now date and time are converted to UTC format 

- src/components/caregiver-schedule/CaregiverAppointment.tsx
- src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
- Caregiver can't accept an expired virtual assessment request.
- if VA date is expired, but appointment start date is not, accept VA button is disabled and reschedule button is active.
- if VA date and appointment start date are expired and appointment status is still Virtual Assesment, both buttons are disabled.
- I check this dates every 15 minutes
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-391)
> fix: Caregiver can't accept an expired VA request

- src/components/account-details/styles.ts
- src/components/admin-appointment-list/AppointmentList.tsx
- src/components/user-list/styles.ts
- src/locales/langs/en.ts
- src/pages/admin-panel/admin-management/index.tsx
- Fixed layout in admin management page
- Added name column to appointment list
- Adapted account details layout
- Made scroll not visible if unused
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?assignee=6257e1835d1e700069af2f1c&selectedIssue=CC-407)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?assignee=6257e1835d1e700069af2f1c&selectedIssue=CC-404)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?assignee=6257e1835d1e700069af2f1c&selectedIssue=CC-403)
> fix: fixed layout in adming-page, added name column to appointments list

- src/components/admin-management/AdminManagement.tsx
- I added text when the admins array is empty.
> fix: add text when admins array is empty

- src/components/admin-management/AdminManagement.tsx
- src/components/user-list/UserList.tsx
- src/pages/admin-panel/account-details/[id].tsx
- fixed delete modal in user list, admin management;
- add text, if users with this search terms are not found;
- if admin goes to edit user profile page from not first page, he is coming back to the same page after.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-398)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-401)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-402)
> fix: admin delete modal
