ZenBit-Tech/ctrlchamps_fe

src/theme/palette.ts

fix: update palette colors

---

src/assets/icons/Cross.tsx
src/assets/icons/NeedHelpIcon.tsx
src/components/modal-need-help/NeedHelpModal.tsx
src/components/modal-need-help/styles.ts
src/components/reusable/header/index.tsx
src/components/reusable/header/styles.ts
src/locales/langs/en.ts
src/theme/colors.ts

create NeedHelpModal component;
add styles;
update Header and styles;
add Cross icon;
add colors, that I needed, to theme;
- I did an awesome feature.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-65)

feat: Need help modal

---

.eslintignore
.eslintrc
__tests__/reset-password/EnterEmail.tsx
__tests__/reset-password/ResetForm.tsx
jest.config.js
jest.setup.js
package-lock.json
package.json
src/components/enter-email/EnterEmail.tsx
src/components/enter-email/constants.ts
src/components/enter-email/hooks.ts
src/components/reset-password-form/ResetPasswordForm.tsx
src/components/reset-password-form/constants.ts
src/components/reset-password-form/index.tsx
src/components/reset-password-form/style.ts
src/components/reset-password-form/validation.ts
src/components/reusable/ErrorText.tsx
src/components/verification/OTPInput.tsx
src/components/verification/Verification.tsx
src/components/verification/VerificationSuccess.tsx
src/components/verification/styles.ts
src/locales/langs/en.ts
src/pages/reset-password/index.tsx

- Changed folder structure, setup test environment, added tests for EnterEmail and ResetForm component, changed EnterEmail error (from alert to text message) to make code more consistent, improved otp logic (inputs accept numbers only not string + input are highlighted in red only after comparing user code with expected code which was generated on backend) 
after submit if code is not valid: 
when one digit of code is changed it is not higlighted in red and button is not disabled:
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-43)

refactor: setup tests + solve inconsistency issues

---

src/components/reusable/sign-up-wrapper/SignUpWrapper.tsx
src/components/reusable/sign-up-wrapper/styles.ts

Add Sign up wrapper to make all registration components in the same style

feat: add signup wrapper

---

src/components/reset-password-form/ResetPasswordForm.tsx
src/components/reusable/index.tsx
src/components/verification/OTPInput.tsx
src/components/verification/Verification.tsx
src/components/verification/styles.ts
src/locales/langs/en.ts

- I added error message if the otp code entered by user was invalid. Divided password and confirm password visibility handling. Adopted style changes.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-43)

fix: fix mentioned issues

---

src/components/sendOTP/AccountVerification.tsx

- Added error message when code does't match
- [Link to JIRA ticket](#https://homecareaid.atlassian.net/jira/software/projects/AC/boards/1?selectedIssue=AC-89)

Demo comment fix: account-verification code doesn't match error display

---

src/components/reusable/header/styles.ts

- Changed header style to suit project's needs.
-

fix: change header style 

---

src/components/complete-profile-fifth/CompleteProfileFifth.tsx
src/components/complete-profile-fifth/validation.ts
src/redux/rootReducer.ts
src/redux/slices/rateSlice.ts
src/redux/store.ts

create Rate Slice;
update variable names;
update store, rootReducer;
update imports
update default from values
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-73)

feat: add rateSlice (Complete Profile 5)

---

src/components/complete-profile-fifth/CompleteProfileFifth.tsx
src/components/login-form/LoginForm.tsx
src/pages/profile/index.tsx

Made request (send hourly rate) in 5th Complete Profile component; 
Add 5th component to main profile page
add setToken after successfull login
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-73)

B&F Compete Profile 5 (Rate)

---

src/components/complete-profile-third/CompleteProfileThird.tsx
src/components/complete-profile-third/constants.ts
src/components/complete-profile-third/hooks.ts
src/components/complete-profile-third/types.ts
src/pages/profile/index.tsx
src/redux/rootReducer.ts
src/redux/slices/servicesSlice.ts
src/redux/store.ts

Made Services slice;
Made request (send services) in 3rd Complete Profile component; 
Move logic to custom hook;
Add 3rd Complete Profile component to main Profile page
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-71)

F&B complete profile 3 (Services)

---

src/components/complete-profile-fourth/CompleteProfileFourth.tsx
src/components/complete-profile-fourth/constants.ts
src/constants/index.ts
src/redux/slices/availableDaysSlice.ts
src/utils/generateTime.ts

- I remade available days slice to suit backend structure and connected fe to be.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-100)

feat: connect profile availability with backend

---

src/components/create-appointment/AppointmentType.tsx
src/components/create-appointment/RecurringAppointment.tsx
src/components/create-appointment/constants.ts
src/components/create-appointment/styles.ts

- I refactored recurring appointment logic as recurring appointment cannot start and be finished in one day
-[x]Performed a self-review of my code

refactor: recurring appointment logic data fix

---

src/components/create-appointment/AppointmentType.tsx
src/components/create-appointment/RecurringAppointment.tsx
src/locales/langs/en.ts

fix: fix appointment bugs and logic

---

src/components/sign-up-second/constants.ts
src/components/sign-up-second/index.tsx
src/components/sign-up-second/validation.ts
src/locales/langs/en.ts

user can't enter more, than 10 characters in phone input;
if user enters 1, the appropriate error message appears;
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-132)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-133)

Bug fix: sign up 2 phone input

---

src/components/profile/bio/Bio.tsx

- I changed input according to the suggestion on the demo (multiline input).
screenshot 1 - initial state of input.
screenshot 2 - input with text.

fix: bio step input

---

src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
src/components/virtual-assessment-request/index.tsx
src/components/virtual-assessment-request/styles.ts
src/components/virtual-assessment-request/types.ts
src/locales/langs/en.ts

- I created drawer for virtual assessment acception/rejection
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?issueType=10001&selectedIssue=CC-126)

feat: created drawer for virtual assessment

---

src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
src/components/appointments/virtual-assessment-modal/styles.ts
src/locales/langs/en.ts
src/redux/api/virtualAssessmentApi.ts

- I made an endpoint so that the seeker could request virtual assessment with the caregiver.

feat: make api endpoint for client's virtual assessment request

---

src/components/appointment-request-modal/AppointmentRequestModal.tsx
src/components/appointment-request-modal/ChildModal.tsx
src/components/appointment-request-modal/types.ts
src/components/appointments/agreement-modal/AgreementModal.tsx
src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
src/components/appointments/appointment-drawer/hooks.ts
src/components/appointments/appointments-list/AppointmentsList.tsx
src/components/appointments/complete-appointment-modal/CompleteAppointmentModal.tsx
src/components/appointments/types.ts
src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
src/components/appointments/virtual-assessment-modal/styles.ts
src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
src/components/virtual-assessment-request/types.ts
src/redux/api/appointmentApi.ts
src/redux/api/virtualAssessmentApi.ts

- updated modals;. 
- updated appointment drawer;
- updated appointments page;
- add getVirtualAssessmentInfo request.

feat: Appointments Page connect

---

src/locales/langs/en.ts
src/redux/api/appointmentApi.ts
src/redux/api/routes.ts

- added getAppointmentsByDate request;
- updated routes, langs.

feat: add get appointments by date request

---

src/components/reusable/profile-wrapper/styles.ts

- I fixed the profile wrapper height to fit content on the screen.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-232?atlOrigin=eyJpIjoiMWM4YzM5YjU5MDU4NGU5MTk3OGJkNjk2MGI2ODVlYjYiLCJwIjoiaiJ9)

fix: profile layout

---

src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx

- I fixed date picker expiration min date.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?selectedIssue=CC-230)

fix: change min date for expiration date picker

---

src/components/complete-profile-fourth/CompleteProfileFourth.tsx
src/components/complete-profile-fourth/hooks.ts
src/components/complete-profile-fourth/styles.ts

- I fixed logic so that if the start time is already chosen, then it would not affect end time.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-269)

fix: fix complete profile availability logic and styles

---

src/components/create-appointment-fourth/CreateAppointmentFourthDrawer.tsx
src/components/profile/bio/Bio.tsx
src/components/reusable/appointment-btn/AppointmentBtn.tsx
src/components/reusable/appointment-btn/styles.ts

- I adjusted button style on the fourth step of creating appointment and fixed redirect complete profile path to the main page.

fix: fix 'create appointment design', adjust button styles, fix redirect complete profile path

---

src/components/confirm-appointment/TasksList.tsx

- I adjusted logic so that after deletion from custom tasks list, the task would not appear in chosen tasks.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-257)

fix: fix custom tasks deletion logic

---

src/components/account-details/personal-info-modal/validation.ts
src/components/complete-profile-second/work-form/validation.ts
src/components/login-form/validation.ts
src/components/profile/bio/validation.ts
src/components/profile/profile-qualification/certificate-form/validation.ts
src/components/reset-password-form/validation.ts
src/components/sign-up-second/validation.ts

- I added trim for string fields for the correct validation.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-229?atlOrigin=eyJpIjoiZjJkZWMxZjI1YTk3NDcxYWIyMDg2MDk1M2FlMjY3Y2YiLCJwIjoiaiJ9)

fix: add trim for string fields

---

src/components/sign-up-third/validation.ts
src/constants/index.ts
src/locales/langs/en.ts

- updated Terms modal title;
- updated sign up validation for the third step
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-271)

fix: updated langs, sign up validation

---

src/components/complete-profile-second/work-form/WorkForm.tsx
src/components/complete-profile-second/work-form/constants.ts
src/components/complete-profile-second/work-form/validation.ts

- fixed date picker end min date in work experience form
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-267)

fix: update constants, date picker

---

src/components/complete-profile-third/CompleteProfileThird.tsx
src/components/complete-profile-third/validation.ts

- add complete profile services validation
- [Link to JIRA ticket][(#https://ticket-url](https://homecareaid.atlassian.net/browse/CC-268))

fix: add complete profile services validation

---

src/components/complete-profile-fourth/hooks.ts
src/components/private-route/PrivateRoute.tsx
src/components/profile/bio/Bio.tsx
src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
src/components/sendOTP/SuccessfulVerification.tsx
src/hooks/useVerification.ts
src/locales/langs/en.ts
src/pages/account-verification/index.tsx
src/redux/api/accountVerificationAPI.ts
src/redux/api/profileCompleteApi.ts
src/redux/slices/userSlice.ts
src/routes/index.ts

- Changed private logic route.
- Set new jwt token when entities update.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-294?atlOrigin=eyJpIjoiYzAwOGYxMzk3MjBkNDFmNmI1NzhiNTUwYWZlZGNlZjciLCJwIjoiaiJ9)

fix: transitions

---

src/components/private-route/constants.ts

- Removed unused contants file.

fix: remove unused constants file

---

src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
src/components/create-appointment/OneTimeAppointment.tsx
src/components/create-appointment/RecurringAppointment.tsx
src/locales/langs/en.ts

- I added constraints and showed errors for user so that they couldn't choose past date.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-300)

fix: fix date bugs connected to user setting past date

---

src/components/log-out-modal/LogOutModal.tsx
src/components/log-out-modal/styles.ts
src/components/reusable/header/FlowHeader.tsx
src/components/reusable/header/styles.ts
src/locales/langs/en.ts
src/redux/slices/userSlice.ts

- add Log out Modal;
- updated Flow header;
- updated user slice (add remove user action)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-147)

feat: add Logout on Complete profile page

---

src/components/appointments/agreement-modal/styles.ts

- updated agreement modal height

fix: agreement modal height

---

src/components/appointments/appointment-drawer/hooks.ts

- add close drawer after rejecting appointment
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-302)

fix: cancel appointment modal

---

src/components/confirm-appointment/ConfirmAppointment.tsx
src/components/faq-accordion/FaqAccordion.tsx
src/components/faq-accordion/types.ts
src/locales/langs/en.ts
src/pages/faq/index.tsx
src/pages/faq/styles.ts
src/pages/transactions/index.tsx
src/routes/index.ts
src/theme/overrides/Accordion.ts

- Added faq page.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-193?atlOrigin=eyJpIjoiZjNjNjk4Mjk4MDA2NDE1ZDg4MzQ5NGRkNTBiYjUxOWYiLCJwIjoiaiJ9)

feat: add faq page

---

src/components/get-help-modal/GetHelpModal.tsx
src/components/modal-need-help/NeedHelpModal.tsx
src/components/reusable/header/Menu.tsx

- updated link text in need help and get help modals;
- added get help modal to menu.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-192)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-129)

fix: need help & get help modals

---

src/components/appointments/appointment-drawer/activity-log-modal/ActivityLogModal.tsx
src/components/appointments/appointment-drawer/activity-log-modal/helpers.ts
src/components/appointments/appointment-drawer/activity-log-modal/styles.ts
src/components/appointments/appointment-status/AppointmentStatus.tsx
src/components/appointments/appointment-status/styles.ts
src/constants/index.ts

- Changed Activity log logic to work with new Finished status of appointment.
- Changed styles of Activity log checkboxes so they can be checked by clicking on label.

refactor: activity log logic

---

src/components/appointments/AppointmentsPage.tsx
src/components/caregiver-schedule/CaregiverSchedulePage.tsx
src/components/private-route/PrivateRoute.tsx
src/constants/index.ts
src/pages/admin-panel/index.tsx
src/pages/caregiver-profile/index.tsx
src/pages/create-appointment/index.tsx
src/pages/profile/index.tsx
src/redux/slices/userSlice.ts
src/routes/index.ts

- Added admin roles.
- Added admin login redirect.
- Changed private routes roles logic.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-233?atlOrigin=eyJpIjoiN2ZlMjMxY2M4MTQwNDE2NDg0NDdkMzhkYTNiZTk0M2EiLCJwIjoiaiJ9)

feat: add admin login

---

src/components/account-details/styles.ts

- little fix of avatar-button styles

fix: avatar button

---

src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
src/redux/api/appointmentApi.ts
src/redux/api/virtualAssessmentApi.ts

- I refactored virtual assessment logic so that the correct virtual assessment info was displayed immediately after rescheduling/changing status. Also, slightly changed drawer, now the seeker can see the caregiver with whom he/she set a virtual assessment.

refactor: refactor virtual assessment logic

---

src/pages/admin-panel/index.tsx

- Removed duplicated line that crashed deployment.

fix: remove duplicated line

---

src/redux/api/activityLogApi.ts
src/redux/api/appointmentApi.ts
src/redux/api/notificationsApi.ts
src/redux/api/virtualAssessmentApi.ts
src/redux/store.ts

- I did refetching data on browser window focus.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-358?atlOrigin=eyJpIjoiMjI5YzA4YWIyNGNkNDA5MGJiNWI3N2M3N2U3NWZkMmIiLCJwIjoiaiJ9)

feat: refetch data on window focus

---

src/constants/index.ts
src/redux/forbiddenErrorMiddleware.ts
src/redux/store.ts

- Create forbidden middleware to catch 403 errors to log out user when jwt token expires.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-360?atlOrigin=eyJpIjoiNDFiYzE3YmQ5MjE2NDAxMmE0Mzk3NDc1YzdiM2ZjMWQiLCJwIjoiaiJ9)

fix: jwt expire

---

src/components/admin-appointment-list/AppointmentList.tsx
src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
src/components/user-list/UserList.tsx

- Fixed bug with admin being able to cancel/accept appointment
- Added outline for role column in users page
- Refetch appointments on delete
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-378)
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-379)

fix: removed drawer_buttons for admins, added greenspan for role

---

src/components/appointments/appointments-list/AppointmentsList.tsx
src/components/appointments/appointments-list/styles.ts
src/components/caregiver-schedule/CaregiverAppointment.tsx
src/components/caregiver-schedule/CaregiverSchedule.tsx
src/components/caregiver-schedule/CaregiverSchedulePage.tsx
src/components/caregiver-schedule/styles.ts
src/components/notifications-list/constants.ts
src/components/reusable/header/MainHeader.tsx
src/components/reusable/header/Menu.tsx
src/components/reusable/header/styles.ts
src/locales/langs/en.ts
src/redux/api/notificationsApi.ts

- I remade the functionality so that the menu could be opened by clicking on avatar/name not only arrow icon, also this functionality is made for appointment blocks. Made calendar visible all the time.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-365)

feat: change style logic

---

src/components/caregiver-schedule/CaregiverAppointment.tsx
src/components/caregiver-schedule/types.ts
src/constants/index.ts

- added new appointment status 'Paused';
- updated appointment type:
- VA appointments shows in date of VA and time of VA displayed; 
- Pending confirmation appointments shows for today.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-363)

feat: update caregiver shedule

---

src/components/admin-appointment-list/AppointmentList.tsx
src/components/admin-appointment-list/styles.ts
src/components/appointments/types.ts
src/locales/langs/en.ts

- I added columns for approved/rejected activity logs in the appointments list table.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-367)

feat: add approved/rejected activity logs columns

---

src/components/account-details/AccountDetails.tsx
src/components/transactions/TransactionsModal.tsx
src/pages/transactions/index.tsx
src/redux/api/transactionsApi.ts

- Fixed transactions pagination.

fix: fix transactions pagination

---

src/components/appointments/appointment-drawer/activity-log-modal/helpers.ts
src/constants/index.ts

- Fixed activity log showing in utc dates.

fix: fix activity log showing in utc

---

src/components/account-details/AccountDetails.tsx
src/components/admin-management/AdminManagement.tsx
src/components/user-list/UserList.tsx

- I did an awesome feature.
- [Link to JIRA ticket](#https://ticket-url)

fix: delet modal user list

---

src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx

- fixed date formats for disable property of buttons "Accept" and "Reschedule" in VA request.
- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/CC-391)

fix: date format in VA request

---

src/components/account-details/AccountDetails.tsx
src/components/account-details/constants.ts

- added pagination for transactions in account details page in admin panel

feat: transactions pagination(edit user by admin)

---

src/components/appointments/virtual-assessment-modal/helpers.ts
src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx

- Removed extra code and changed displayed VA time
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?selectedIssue=CC-415)

fix: VA time now displayed in local time, not in appointments time

---

src/components/admin-appointment-list/AppointmentList.tsx
src/components/admin-management/AdminManagement.tsx
src/components/admin-management/tasks/TasksManagement.tsx
src/components/user-list/UserList.tsx
src/constants/index.ts

- Fixed bug which we noticed on demo that we can't search properly with pagination

fix: fixed bug with search on admin panel

---

src/components/create-appointment-fourth/CreateAppointmentFourth.tsx
src/components/create-appointment-fourth/helpers.ts
src/components/create-appointment-fourth/hooks.ts
src/components/create-appointment-fourth/types.ts
src/redux/slices/appointmentSlice.ts

- Made F&B for filtering caregivers on their availability
- [Link to JIRA ticket](https://homecareaid.atlassian.net/jira/software/projects/CC/boards/1?selectedIssue=CC-389)

feat: updated filter for available caregivers
